[WIP] Get terraform files from remote repo
sabre1041/argocd-terraform-controller pull request #16
Opened 2022-05-13 21:03 UTC by josephsawaya

This commit implements getting the terraform files
from the remote repository using the argocd-repo-server.

This commit implements an argocd plugin which is necessary
fetching the remote terraform files. This plugin calls a script
which runs in the path specified by the Terraform CR.

This commit creates a RepoClient to call the GenerateManifests
function in the repo server to make use of this plugin and get
the files. Finally it prints the contents of the manifests
returned by the the repo server.

Fixes: #4 

Depends on: #14

2022-05-16 18:56 UTC, jeffvance commented on api/v1alpha1/terraform_types.go
> +*/
Should this state constants be defined?

2022-05-16 18:57 UTC, jeffvance commented on controllers/terraform_controller.go
> +	context "context"
why an alias here?

2022-05-27 06:01 UTC, sabre1041 requested changes
Initial feedback

2022-05-27 06:01 UTC, sabre1041 commented on Makefile
> +KUTTL_URL := https://github.com/kudobuilder/kuttl/releases/download/v$(KUTTL_VERSION)/kubectl-kuttl_$(KUTTL_VERSION)_linux_x86_64
Binary to retrieve should take account of the platform/operating system that it is being installed on

2022-05-27 06:01 UTC, sabre1041 commented on config/manager/manager.yaml
> +  name: argocd
Lets keep these as the default `system` namespace. Values will be dynamically updated at runtime

2022-05-27 06:01 UTC, sabre1041 commented on config/manager/manager.yaml
> +        imagePullPolicy: Always
This is good for development, but not needed in production as it should be referencing the digest

2022-05-27 06:01 UTC, sabre1041 commented on config/samples/_v1alpha1_terraform.yaml
> +    repoURL: https://github.com/josephsawaya/terraform-test.git
Do we want to incorporate the sample into this repository?

2022-05-27 06:01 UTC, sabre1041 commented on terraform-generate/kustomize-install/argocd-repo-server.yaml
> +            https://raw.githubusercontent.com/josephsawaya/argocd-terraform-controller/dev/terraform-generate/generate.sh &&
This needs to be updated for this repository

2022-05-28 21:11 UTC, sabre1041 requested changes
I tried to run the test framework without success. Are there steps that need to be followed? Add to `README.md`?

2022-05-28 21:11 UTC, sabre1041 commented on Makefile
> +.PHONY: kuttl
Download fails if `bin` folder not present first

2022-05-28 21:11 UTC, sabre1041 commented on Makefile
> +KUTTL_URL := https://github.com/kudobuilder/kuttl/releases/download/v$(KUTTL_VERSION)/kubectl-kuttl_$(KUTTL_VERSION)_linux_x86_64
Heres an example:

```
# Platform
ifeq ($(OS),Windows_NT)
  PLATFORM := windows
else
  UNAME_S = $(shell uname -s)
  ifeq ($(UNAME_S),Linux)
    PLATFORM := linux
  endif
  ifeq ($(UNAME_S),Darwin)
    PLATFORM := darwin
  endif
endif
```

`$(PLATFORM)` can then be added to the `KUTTL_URL`

2022-05-28 21:11 UTC, sabre1041 commented on Makefile
> +test-e2e: kuttl ## Run e2e tests. Requires cluster w/ Scribe already installed
add `test-kuttl/kubeconfig` to `.gitignore`

2022-06-01 18:35 UTC, josephsawaya commented
> I tried to run the test framework without success. Are there steps that need to be followed? Add to `README.md`?

So the test framework changes are a part of #13. I realize now that having many PRs open that depend on each other is probably confusing, so I'm going to close my previous PR, and try to remove the commits in this PR that are a part of #13.

2022-06-15 09:03 UTC, sabre1041 approved these changes
LGTM

2022-06-15 09:03 UTC, merged